### ISSUE TITLE
Please add a License.txt file to your repo

### ISSUE THREAD

**Issue by abchatra** [sparkfun/pxt-gamer-bit#8]
MakeCode extensions need to be MIT license

**Comment by abchatra** [comment]
Customer is asking for the same as well: https://github.com/microsoft/pxt-microbit/issues/1769#issuecomment-1536644389

**Comment by abchatra** [comment]
@loricrotser

**Comment by loricrotser** [comment]
@abchatra

This is done. Apologies for the delay.

**Comment by abchatra** [comment]
Thanks @loricrotser
